name: Push to remote

on:
  push:
    branches:
      - "**"

jobs:
  install-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
      - name: Push to remote
        run: |-
          npm run push -- docs/s-petstore.yaml \
          --organization default \
          --project 'cicd-pushes' \
          --mountPath 'docs/remotes/cicd' \
          --branch "${{ github.ref_name }}" \
          --author "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>" \
          --message "${{ github.event.head_commit.message }}" \
          --domain 'https://app.lab1.blueharvest.cloud'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_AUTHORIZATION }}
